on: 
  workflow_dispatch:

on:
  project_card:
    types: [created, deleted]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Hello from Step 1"
      - name: Step 2
        run: echo "Hello from Step 2"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: GitHub Action from the GitHub Marketplace
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'Team 2 cow says moo!'
        color: 'red'